-- Database Creation and Backup --

create database RPG
default character set utf8
default collate utf8_general_ci;

use RPG;

create table racas(
	id_raca int primary key not null auto_increment,
    nome varchar(50) not null,
	up_valor_habilidade text,
	proeficiencias text,
    skills text,
    idiomas text,
    classes_fav text
    ) default charset = utf8;
    

insert into racas
(nome, up_valor_habilidade, proeficiencias, skills, idiomas, classes_fav)
values
(
'Anão da Colina',
'Constituição +2 / Sabedoria +1',
'Machados de Batalha, Machadinhas, Martelos Leves, Martelos de Guerra e uma ferramenta de artesão à sua escolha entre: ferramentas de ferreiro, suprimentos de cervejeiro ou ferramentas de pedreiro.',
'Visão no Escuro. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra.\nTenacidade Anã. Seu máximo de pontos de vida aumentaram em 1, e cada vez que o anão da colina sobe um nível, ele recebe 1 ponto de vida adicional.' ,
'Comum, Anão',
'Bárbaro, Clérigo, Druida, Guerreiro ou Paladino.'
),
(
'Anão da Montanha',
'Constituição +2 / Força +2',
'Armaduras leves e médias, Machados de Batalha, Machadinhas, Martelos Leves, Martelos de Guerra e uma ferramenta de artesão à sua escolha entre: ferramentas de ferreiro, suprimentos de cervejeiro ou ferramentas de pedreiro.',
'Visão no Escuro. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra.',
'Comum, Anão',
'Bárbaro, Clérigo, Druida, Guerreiro ou Paladino.'
),
(
'Alto Elfo',
'Destreza +2 / Inteligência +1',
'Perícia Percepção, Espadas Longas, Espadas Curtas, Arcos Longos e Arcos Curtos.',
'Visão no Escuro. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra.\nTranse. Elfos não precisam dormir. Ao invés disso, eles meditam profundamente, permanecendo semiconscientes, durante 4 horas por dia. Depois de descansar dessa forma, você ganha os mesmos benefícios que um humano depois de 8 horas de sono.',
'Comum, Élfico',
'Qualquer classe conjuradora, Guerreiro, Ladino ou Ranger.'
),
(
'Elfo da Floresta',
'Destreza +2 / Sabedoria +1',
'Perícia Percepção, Espadas Longas, Espadas Curtas, Arcos Longos e Arcos Curtos.',
'Visão no Escuro. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra.\nTranse. Elfos não precisam dormir. Ao invés disso, eles meditam profundamente, permanecendo semiconscientes, durante 4 horas por dia. Depois de descansar dessa forma, você ganha os mesmos benefícios que um humano depois de 8 horas de sono.',
'Comum, Élfico',
'Qualquer classe conjuradora, Guerreiro, Ladino ou Ranger.'
),
(
'Elfo Negro (Drow)',
'Destreza +2 / Carisma +1',
'Perícia Percepção, Rapieiras, Espadas Curtas e Bestas de Mão.',
'Visão no Escuro Superior. Você enxerga na penumbra a até 36 metros como se fosse luz plena, e no escuro como se fosse na penumbra.\nTranse. Elfos não precisam dormir. Ao invés disso, eles meditam profundamente, permanecendo semiconscientes, durante 4 horas por dia. Depois de descansar dessa forma, você ganha os mesmos benefícios que um humano depois de 8 horas de sono.\nSensibilidade à Luz Solar. Você possui desvantagem nas jogadas de ataque e testes de Sabedoria (Percepção) relacionados a visão quando você, o alvo do seu ataque, ou qualquer coisa que você está tentando perceber, esteja sob luz solar direta',
'Comum, Élfico',
'Qualquer classe conjuradora, Guerreiro, Ladino ou Ranger.'
),
(
'Meio Elfo',
'Carisma +2 / Dois Atributos de Escolha +1',
'Duas Perícias à Sua Escolha',
'Visão no Escuro. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra.',
'Comum, Élfico',
'Bardo, Feiticeiro, Clérigo ou Paladino (Classes Cojuradoras)'
),
(
'Halfling Pés Leves',
'Destreza +2 / Carisma +1',
null,
'Sortudo. Quando você obtiver um 1 natural em uma jogada de ataque, teste de habilidade ou teste de resistência, você pode jogar de novo o dado e deve utilizar o novo resultado.\nFurtividade Natural. Você pode tentar se esconder mesmo quando possuir apenas a cobertura de uma criatura que for no mínimo um tamanho maior que o seu.',
'Comum, Halfling',
'Bardo, Ladino ou Ranger.'
),
(
'Halfling Robusto',
'Destreza +2 / Constituição +1',
null,
'Sortudo. Quando você obtiver um 1 natural em uma jogada de ataque, teste de habilidade ou teste de resistência, você pode jogar de novo o dado e deve utilizar o novo resultado.',
'Comum, Halfling',
'Bardo, Ladino ou Ranger.'
),
(
'Humano',
'Todos os Atributos +1',
null,
null,
'Comum',
'Qualquer uma.'
),
(
'Humano Variante (!)',
'Dois Atributos à Escolha +2',
'Uma perícia à sua escolha.',
'Um talento à sua escolha.',
'Comum',
'Qualquer uma.'
),
(
'Draconato',
'Força +2 / Carisma +1',
null,
'Ancestral Dracônico. Você possui um ancestral dracônico, que te dá uma arma de sopro e resistência a dano, pelo tipo de dragão escolhido.',
'Comum, Dracônico',
'Guerreiro, Paladrino, Ranger(corpo-a-corpo) ou Clérigos(focados em combate).'
),
(
'Gnomo da Floresta',
'Inteligência +2 / Destreza +1',
null,
'Visão no Escuro. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra.\nEsperteza Gnômica. Você possui vantagem em todos os testes de resistência de Inteligência, Sabedoria e Carisma contra magia.\nIlusionista Nato. Você conhece o truque ilusão menor. Inteligência é sua habilidade usada para conjurá-la.\nFalar com Bestas Pequenas. Gnomos da floresta amam os animais e normalmente possuem esquilos, doninhas, coelhos, toupeiras, pica-paus e outras criaturas como amados animais de estimação.',
'Comum, Gnômico',
'Bardo, Mago ou Ladino.'
),
(
'Gnomo das Rochas',
'Inteligência +2 / Constituição +1',
null,
'Visão no Escuro. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra.\nEsperteza Gnômica. Você possui vantagem em todos os testes de resistência de Inteligência, Sabedoria e Carisma contra magia.',
'Comum, Gnômico',
'Bardo, Mago ou Ladino.'
),
(
'Meio-Orc',
'Força +2 / Constituição +1',
'Perícia Intimidação',
'Visão no Escuro. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra.\nResistência Implacável. Quando você é reduzido a 0 pontos de vida você não é completamente morto e pode voltar para 1 ponto de vida. Só se pode usar esse talento uma vez por descanso longo.\nAtaques Selvagens. Quando você atinge um ataque crítico com uma arma corpo-a-corpo, você pode rolar um dos dados de dano da arma mais uma vez e adicioná-lo ao dano extra causado pelo acerto crítico.',
'Comum, Orc',
'Bárbaro ou Guerreiro.'
),
(
'Tiefling Infernal',
'Carisma +2 / Inteligência +1',
null,
'Visão no Escuro. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra.\nResistência Infernal. Você possui resistência a dano ígneo.',
'Comum, Infernal',
'Bardo, Bruxo, Feiticeiro, Ladino(focado em Enganação) ou Paladino(focado em magia).'
),
(
'Tiefling Abissal',
'Carisma +2 / Constituição +1',
null,
'Visão no Escuro. Você enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse na penumbra.\nResistência Abissal. Seus pontos de vida máximos aumentam pela metade do seu nível (mínimo 1).',
'Comum, Abissal',
'Bardo, Bruxo, Feiticeiro, Ladino(focado em Enganação) ou Paladino(focado em magia).'
);



create table classes(
	id_classe int primary key not null auto_increment,
    nome varchar(50) not null,
	dado_de_vida varchar(20),
    vida int,
	habilidade text,
	tem_magia boolean,
    espaco_magia int
    ) default charset = utf8;
    
    
insert into classes
(nome, dado_de_vida, vida, habilidade, tem_magia, espaco_magia)
values
('Bárbaro', '1d12', 12, 'Fúria: Pode entrar em fúria para ganhar bônus de dano e resistência a dano.', False, null),
('Bardo', '1d8', 8, 'Magias: Começa com algumas magias de 1º nível e conhecimento de truques.', True, 2),
('Clérigo', '1d8', 8, 'Magias Clericais: Pode lançar magias clericais de 1º nível.', True, 2),
('Druida', '1d8', 8, 'Transformação Selvagem: Pode se transformar em uma criatura animal.', True, 2),
('Feiticeiro', '1d6', 6, 'Fonte de Magia: Conhece e pode lançar um número limitado de magias.', True, 2)
('Guerreiro', '1d10', 10, 'Ataque Extra: Pode realizar um segundo ataque em sua ação.', False, null),
('Ladino', '1d8', 8, 'Ataque Furtivo: Pode causar dano extra ao atacar surpreendendo o inimigo.', False, null),
('Mago', '1d6', 6, 'Livro de Sombras: Pode aprender e preparar magias de 1º nível.', True, 3),
('Paladino', '1d10', 10, 'Canalizar Divindade: Pode canalizar poder divino para efeitos específicos.', False, null),
('Patrulheiro', '1d10', 10, 'Rastreio: Possui habilidades de rastreamento e sobrevivência.', False, null),
('Bruxo', '1d8', 8, 'Pacto Arcano: Faz um pacto com uma entidade sobrenatural.', True, 1),
('Monge', '1d8', 8, 'Ataque Descuidado: Pode atacar como uma ação bônus.', False, null);




create table armas(
	id_arma int primary key not null auto_increment,
    nome varchar(30) not null,
	dano_e_tipo varchar(50),
    alcance varchar(50),
	propriedades text,
    tipo varchar(50)
    ) default charset = utf8;
    
insert into armas
(nome, dano_e_tipo, alcance, propriedades, tipo)
values
('Adaga', '1d4 perfurante', 'Corpo a Corpo', 'Finesse, leve, arremesso (20 pés).', 'Corpo a Corpo Simples'),
('Porrete', '1d4 concussivo', 'Corpo a Corpo', 'Leve.', 'Corpo a Corpo Simples'),
('Maça', '1d6 concussivo', 'Corpo a Corpo', null, 'Corpo a Corpo Simples'),
('Cajado', '1d6 concussivo', 'Corpo a Corpo', 'Versátil (pode ser usado com uma ou duas mãos, dobrando o alcance).', 'Corpo a Corpo Simples'),
('Espada Curta', '1d6 perfurante/cortante', 'Corpo a Corpo', 'Finesse, leve.', 'Corpo a Corpo Marcial'),
('Machado de Batalha', '1d8 cortante', 'Corpo a Corpo', 'Versátil (pode ser usado com uma ou duas mãos).', 'Corpo a Corpo Marcial'),
('Maça Espinhenta', '1d8 concussivo', 'Corpo a Corpo', null, 'Corpo a Corpo Marcial'),
('Rapieira', '1d8 perfurante', 'Corpo a Corpo', 'Finesse', 'Corpo a Corpo Marcial'),
('Arco Curto', '1d6 perfurante', '80 Pés / 320 Pés (Desvantagem)', 'Leve, munição(flechas).', 'Distância Simples'),
('Besta Leve', '1d8 perfurante', '80 Pés / 320 Pés (Desvantagem)', 'Munição(virotes ou dardos).', 'Distância Simples'),
('Arco Longo', '1d8 perfurante', '150 Pés / 600 Pés (Desvantagem)', 'Munição(flechas).', 'Distância Marcial'),
('Besta Pesada', '1d10 perfurante', '100 Pés / 400 Pés (Desvantagem)', 'Munição(virotes ou dardos).', 'Distância Marcial'),
('Besta Leve de Mão', '1d6 perfurante', '30 Pés / 120 Pés (Desvantagem)', 'Leve, munição(virotes ou dardos).', 'Distância Marcial'),
('Azagaia', '1d6 perfurante', 'Corpo a Corpo', 'Arremesso(20 Pés / 60 Pés (Desvantagem)), versátil (pode ser usado com uma ou duas mãos).', 'Corpo a Corpo / Distância');







create table magias(
	id_magia int primary key not null auto_increment,
    nome varchar(30) not null,
    circulo varchar(10) not null,
    tempo_conj varchar(20) not null,
    alcance varchar(20) not null,
    componentes varchar(10),
    duracao varchar(20) not null,
    material text,
    efeito text,
    nivel_maior text
    ) default charset = utf8;

insert into magias
(nome, circulo, tempo_conj, alcance, componentes, duracao, material, efeito, nivel_maior)
values
('Amizade', 'Truque', '1 Ação', 'Pessoal', 'S, M', 'Até 1 minuto', 'uma pequena quantidade de maquiagem aplicada ao rosto durante a conjuração da magia', 'Pela duração, você terá vantagem em todos os testes de Carisma direcionados a uma criatura, à sua escolha, que não seja hostil a você. Quando a magia acabar, a criatura perceberá que você usou maia para influenciar o humor dela, e ficará hostil a você. Uma criatura propensa a violência irá atacar você. Outra criatura pode buscar outras formas de retaliação (a critério do Mestre), dependendo da natureza da sua interação com ela.', null),
('Ataque Certeiro', 'Truque', '1 Ação', '9 Metros', 'S', 'Até 1 rodada', null, 'Você estende sua mão e aponta o dedo para um alvo no alcance. Sua magia garante a você uma breve intuição sobre as defesas do alvo. No seu próximo turno, você terá vantagem na primeira jogada de ataque contra o alvo, considerando que essa magia não tenha acabado.', null),
('Bordão Místico', 'Truque', '1 Ação Bônus', 'Toque', 'V, S, M', '1 Minuto', 'visco, uma folha de trevo e uma clava ou bordão', 'A madeira de uma clava ou bordão, que você esteja segurando, é imbuída com o poder da natureza. Pela duração, você pode usar sua habilidade de conjuração ao invés da sua Força para as jogadas de ataque e dano corpo-a-corpo usando essa arma, e o dado de dano da arma se torna um d8. A arma também se torna mágica, se ela já não for. A magia acaba se você conjura-la novamente ou se você soltar a arma.', null),
('Chama Sagrada', 'Truque', '1 Ação', '18 Metros', 'V, S', 'Instantânea', null, 'Radiação similar a uma chama desce sobre uma criatura que você possa ver, dentro do alcance. O alvo deve ser bem sucedido num teste de resistência de Destreza ou sofrerá 1d8 de dano radiante. O alvo não recebe qualquer benefício de cobertura contra esse teste de resistência.', 'O dano da magia aumenta em 1d8 quando você alcança o 5° nível (2d8), 11° nível (3d8) e 17° nível (4d8).'),
('Chicote de Espinhos', 'Truque', '1 Ação', '9 Metros', 'V, S, M', 'Instantânea', 'uma muda de uma planta com espinhos', 'Você cria um longo chicote de vinhas coberto por espinhos que chicoteia, ao seu comando, em direção de uma criatura dentro do alcance. Realize um ataque corpo-a- corpo com magia contra o alvo. Se o ataque atingir, a criatura sofrerá 1d6 de dano perfurante e, se a criatura for Grande ou menor, você a puxa até 3 metros para perto de você.', 'O dano dessa magia aumenta em 1d6 quando você alcança o 5° nível (2d6), 11° nível (3d6) e 17° nível (4d6).'),
('Consertar', 'Truque', '1 Minuto', 'Toque', 'V, S, M', 'Instantânea', 'dois imãs', 'Essa magia repara um única quebra ou fissura em um objeto que você tocar, como um elo quebrado de uma corrente, duas metades de uma chave partida, um manto rasgado ou o vazamento em um odre. Contanto que a quebra ou fissura não tenha mais de 30 centímetros em qualquer dimensão, você pode remenda-la, não deixando qualquer vestígio do dano anterior. Essa magia pode reparar fisicamente um item mágico ou constructo, mas a magia não irá restaurar a magia em tais objetos.', null),
('Criar Chamas', 'Truque', '1 Ação', 'Pessoal', 'V, S', '10 Minutos', null, 'Uma chama tremulante aparece na sua mão. A chama permanece ai pela duração e não machuca nem você nem seu equipamento. A chama emite luz plena num raio de 3 metros e penumbra por 3 metros adicionais. A magia acaba se você dissipa-la usando uma ação ou se conjura-la novamente. Você pode, também, atacar com a chama, no entanto, fazer isso acaba com a magia. Quando você conjura essa magia ou com uma ação em um turno posterior, você pode arremessar a chama numa criatura a até 9 metros de você. Faça um ataque à distância com magia. Se atingir, o alvo sofre 1d8 de dano de fogo.', 'O dano dessa magia aumenta em 1d8 quando você alcança o 5° nível (2d8), 11° nível (3d8) e 17° nível (4d8).'),
('Druidismo', 'Truque', '1 Ação', '9 Metros', 'V, S', 'Instantânea', null, 'Sussurrando para os espíritos da natureza, você cria um dos seguintes efeitos, dentro do alcance:\nVocê cria um efeito sensorial minúsculo e inofensivo que prevê como será o clima na sua localização pelas próximas 24 horas. O efeito deve se manifestar como um globo dourado para céu claro, uma nuvem para chuva, flocos de neve para nevasca e assim por diante. Esse efeito persiste por 1 rodada.\nVocê faz uma flor florescer, uma semente brotar ou um folha amadurecer, instantaneamente.\nVocê cria um efeito sensorial inofensivo instantâneo, como folhas caindo, um sopro de vento, o som de um pequeno animal ou o suave odor de um repolho. O efeito deve caber num cubo de 1,5 metro.\nVocê, instantaneamente, acende ou apaga uma vela, tocha ou fogueira pequena.', null),
('Espirro Ácido', 'Truque', '1 Ação', '18 Metros', 'V, S', 'Instantânea', null, 'Você arremessa uma bolha de ácido. Escolha uma criatura dentro do alcance, ou escolha duas criaturas dentro do alcance que estejam a 1,5 metro uma da outra. Um alvo deve ser bem sucedido num teste de resistência de Destreza ou sofrerá 1d6 de dano ácido.', 'O dano dessa magia aumenta em 1d6 quando você alcança o 5° nível (2d6), 11° nível (3d6) e 17° nível (4d6)'),
('Estabilizar', 'Truque', '1 Ação', 'Toque', 'V, S', 'Instantânea', null, 'Você toca uma criatura viva que esteja com 0 pontos de vida. A criatura é estabilizada. Essa magia não afeta mortos-vivos ou constructos.', null),
('Globos de Luz', 'Truque', '1 Ação', '36 Metros', 'V, S, M', 'Até 1 minuto', 'um pouco de fósforo ou wychood ou um inseto luminoso', 'Você cria até quatro luzes do tamanho de tochas dentro do alcance, fazendo-as parecerem tochas, lanternas ou esferas luminosas que flutuam no ar pela duração. Você também pode combinar as quatro luzes em uma forma luminosa, vagamente humanoide, de tamanho Médio. Qualquer que seja a forma que você escolher, cada luz produz penumbra num raio de 3 metros. Com uma ação bônus, no seu turno, você pode mover as luzes, até 18 metros, para um novo local dentro do alcance. Uma luz deve estar a, pelo menos, 6 metros de outra luz criada por essa magia e uma luz some se exceder o alcance da magia.', null),
('Ilusão Menor', 'Truque', '1 Ação', '9 Metros', 'V, M', '1 Minuto', 'um pouco de lã', 'Você cria um som ou uma imagem de um objeto, dentro do alcance, que permanece pela duração. A ilusão também termina se você dissipa-la usando uma ação ou conjurar essa magia novamente. Se você criar um som, seu volume pode variar entre um sussurro até um grito. Pode ser a sua voz, a voz de outrem, o rugido de um leão, batidas de tambor ou qualquer outro som que você quiser. O som permanece no mesmo volume durante toda duração ou você pode fazer sons distintos em momentos diferentes, antes da magia acabar. Se você criar uma imagem de um objeto – como uma cadeira, pegadas de lama ou um pequeno baú – ela não pode ter mais de 1,5 metro cúbico. A imagem não pode produzir som, luz, cheiro ou qualquer outro efeito sensorial. Interação física com a imagem revelará que ela é uma ilusão, já que as coisas podem atravessa-la. Se uma criatura usar sua ação para examinar a imagem, ela pode determinar que ela é uma ilusão se obtiver sucesso num teste de Inteligência (Investigação) contra a CD da magia. Se uma criatura discernir a ilusão como sendo isso, a ilusão se tornará suave para a criatura.', null),
('Luz', 'Truque', '1 Ação', 'Toque', 'V, M', '1 Hora', 'um vaga-lume ou musgo fosforescente', 'Você toca um objeto que não tenha mais 3 metros em qualquer dimensão. Até a magia acabar, o objeto emite luz plena num raio de 6 metros e penumbra por 6 metros adicionais. Cobrir o objeto completamente com alguma coisa opaca bloqueará a luz. A magia termina se você conjura-la novamente ou dissipa-la com uma ação. Se você tentar afetar um objeto segurado ou vestido por uma criatura hostil, a criatura deve ser bem sucedida num teste de Destreza para evitar a magia.', null),
('Mãos Mágicas', 'Truque', '1 Ação', '9 Metros', 'V, S', '1 Minuto', null, 'Uma mão espectral flutuante aparece num ponto, à sua escolha, dentro do alcance. A mão permanece pela duração ou até você dissipa-la com uma ação. A mão some se estiver a mais de 9 metros de você ou se você conjurar essa magia novamente.\nVocê pode usar sua ação para controlar a mão. Você pode usar a mão para manipular um objeto, abrir uma porta ou recipiente destrancado, guardar ou pegar um item de um recipiente aberto ou derramar o conteúdo de um frasco. Você pode mover a mão até 9 metros a cada vez que a usa.\nA mão não pode atacar, ativar itens mágicos ou carregar mais de 5 quilos.', null),
('Mensagem', 'Truque', '1 Ação', '36 Metros', 'V, S, M', '1 Rodada', 'um pedaço curto de fio de cobre', 'Você aponta seu dedo para uma criatura dentro do alcance e sussurra uma mensagem. O alvo (e apenas ele) ouvi a mensagem e pode responder com um sussurro que apenas você pode ouvir.\nVocê pode conjurar essa magia através de objetos sólidos se você tiver familiaridade com o alvo. Silêncio mágico, 30 centímetros de rocha, 2,5 centímetros de metal comum, uma fina camada de chumbo, ou 90 centímetros de madeira ou terra bloqueiam a magia. A magia não precisa seguir uma linha reta e pode viajar livremente, dobrando esquinas ou através de aberturas.', null),
('Orientação', 'Truque', '1 Ação', 'Toque', 'V, S', 'Até 1 minuto', null, 'Você toca uma criatura voluntária. Uma vez, antes da magia acabar, o alvo pode rolar um d4 e adicionar o número rolado a um teste de habilidade a escolha dele. Ele pode rolar o dado antes ou depois de realizar o teste de habilidade. Após isso, a magia termina.', null),
('Prestidigitação', 'Truque', '1 Ação', '3 Metros', 'V, S', 'Até 1 hora', null, 'Essa magia é um truque mágico simples que conjuradores iniciantes usam para praticar. Você cria um dos seguintes efeitos mágicos dentro do alcance:\nVocê cria, instantaneamente, um efeito sensorial inofensivo, como uma chuva de faíscas, um sopro de vento, notas musicais suaves ou um odor estranho.\nVocê, instantaneamente, acende ou apaga uma vela, uma tocha ou uma pequena fogueira.\nVocê, instantaneamente, limpa ou suja um objeto de até 1 metro cúbico.\nVocê esfria, esquenta ou melhora o sabor de até 1 metro cubico de matéria inorgânica por 1 hora.\nVocê faz uma cor, uma pequena marca ou um símbolo aparecer em um objeto ou superfície por 1 hora.\nVocê cria uma bugiganga não-mágica ou uma imagem ilusória que caiba na sua mão e que dura até o final do seu próximo turno.\nSe você conjurar essa magia diversas vezes, você pode ter até três dos seus efeitos não-instantâneos ativos, ao mesmo tempo, e você pode dissipar um desses efeitos com uma ação.', null),
('Proteção Contra Lâminas', 'Truque', '1 Ação', 'Pessoal', 'V, S', '1 Rodada', null, 'Você estende suas mãos e desenha um símbolo de proteção no ar. Até o final do seu próximo turno, você terá resistência contra dano de concussão, cortante e perfurante causado por ataques com armas.', null),
('Raio de Fogo', 'Truque', '1 Ação', '36 Metros', 'V, S', 'Instantânea', null, 'Você arremessa um cisco de fogo em uma criatura ou objeto dentro do alcance. Faça um ataque à distância com magia contra o alvo. Se atingir, o alvo sofre 1d10 de dano de fogo. Um objeto inflamável atingido por essa magia, incendeia se não estiver sendo vestido ou carregado', 'O dano dessa magia aumenta em 1d10 quando você alcança o 5° nível (2d10), 11° nível (3d10) e 17° nível (4d10)'),
('Raio de Gelo', 'Truque', '1 Ação', '18 Metros', 'V, S', 'Instantânea', null, 'Um raio frigido de luz azul clara parte em direção de uma criatura, dentro do alcance. Realize um ataque à distância com magia contra o alvo. Se atingir, ele sofre 1d8 de dano de frio e seu deslocamento é reduzido em 3 metros até o começo do seu próximo turno.', 'O dano da magia aumenta em 1d8 quando você alcança o 5° nível (2d8), 11° nível (3d8) e 17° nível (4d8)'),
('Rajada de Veneno', 'Truque', '1 Ação', '3 Metros', 'V, S', 'Instantâneamente', null, 'Você ergue sua mão em direção de uma criatura que você possa ver, dentro do alcance e projeta um sopro de gás tóxico da sua palma. A criatura deve ser bem sucedida num teste de resistência de Constituição ou sofrerá 1d12 de dano de veneno.', 'O dano dessa magia aumenta em 1d12 quando você alcança o 5° nível (2d12), 11° nível (3d12) e 17° nível (4d12)'),
('Rajada Mística', 'Truque', '1 Ação', '36 Metros', 'V, S', 'Instantâenamente', null, 'Um feixe de energia crepitante vai em direção a uma criatura dentro do alcance. Realize uma jogada de ataque à distância com magia contra o alvo. Se atingir, o alvo sofre 1d10 de dano de energia.\nA magia cria mais de um feixe quando você alcança níveis elevados: dois feixes no 5° nível, três feixes no 11° nível e quatro feixes no 17° nível. Você pode direcionar os feixes para o mesmo alvo ou para alvos diferentes. Realize jogadas de ataque separadas para cada feixe.', null),
('Resistência', 'Truque', '1 Ação', 'Toque', 'V, S, M', 'Até 1 minuto', 'um manto em miniatura', 'Você toca uma criatura voluntária. Uma vez, antes da magia acabar, o alvo pode rolar um d4 e adicionar o valor jogado a um teste de resistência de sua escolha. Ele pode rolar o dado antes ou depois de realizar o teste de resistência. Então, a magia termina.', null),
('Taumaturgia', 'Truque', '1 Ação', '9 Metros', 'V', 'Até 1 minuto', null, 'Você manifesta pequenas maravilhas, um sinal de poder sobrenatural, dentro do alcance. Você cria um dos seguintes efeitos mágicos dentro do alcance:\nSua voz ressoa com o triplo do volume normal por 1 minuto.\nVocê provoca tremores inofensivos no solo por 1 minuto.\nVocê cria, instantaneamente, um som que se origina de um ponto, à sua escolha, dentro do alcance, como o barulho de um trovão, o gralhar de um corvo ou sussurros sinistros.\nVocê, instantaneamente, faz uma porta ou janela destrancada se abrir ou se fechar.\nVocê altera a aparência dos seus olhos por 1 minuto.\nSe você conjurar essa magia diversas vezes, você pode ter até três dos efeitos de 1 minuto ativos por vez, e você pode dissipar um desses efeitos com uma ação.', null),
('Toque Arrepiante', 'Truque', '1 Ação', '36 Metros', 'V, S', '1 Rodada', null, 'Você cria uma mão esquelética fantasmagórica no espaço de uma criatura, dentro do alcance. Realize um ataque à distância com magia contra a criatura para afeta-la com o frio sepulcral. Se atingir, a criatura sofre 1d8 de dano necrótico e não poderá recuperar pontos de vida até o início do seu próximo turno. Até lá, a mão ficará presa ao alvo.\nSe você atingir um alvo morto-vivo, ele terá desvantagem nas jogadas de ataque contra você até o final do seu próximo turno.', 'O dano dessa magia aumenta em 1d8 quando você alcança o 5° nível (2d8), 11° nível (3d8) e 17° nível (4d8)'),
('Toque Chocante', 'Truque', '1 Ação', 'Toque', 'V, S', 'Instantânea', null, 'Eletricidade surge da sua mão para transmitir um choque em uma criatura que você tentar tocar. Faça um ataque corpo-a-corpo com magia contra o alvo. Você tem vantagem na jogada de ataque se o alvo estiver vestindo qualquer armadura de metal. Se atingir, o alvo sofre 1d8 de dano elétrico e não pode usar reações até o início do próximo turno dele.', 'O dano da magia aumenta em 1d8 quando você alcança o 5° nível (2d8), 11° nível (3d8) e 17° nível (4d8)'),
('Zombaria Viciosa', 'Truque', '1 Ação', '18 Metros', 'V', 'Instantânea', null, 'Você libera uma série de insultos atados com encantamentos sutis numa criatura que você possa ver, dentro do alcance. Se o alvo puder ouvir você (apesar de não precisar compreende-lo), ele deve ser bem sucedido num teste de resistência de Sabedoria ou sofrerá 1d4 de dano psíquico e terá desvantagem na próxima jogada de ataque que ele fizer antes do final do próximo turno dele.', 'O dano dessa magia aumenta em 1d4 quando você alcança o 5° nível (2d4), 11° nível (3d4) e 17° nível (4d4)');
('Alarme', '1º Círculo', '1 Minuto', '9 Metros', 'V, S, M', '8 Horas', 'um pequeno sino e um pequeno fio de prata', 'Você coloca um alarme para intrusos desavisados. Escolha uma porta, uma janela ou uma área dentro do alcance que não seja maior que 6 metros cúbicos. Até a magia acabar, um alarme alerta você sempre que uma criatura Miúda ou maior tocarem ou entrarem na área protegida. Quando você conjura a magia, você pode designar as criaturas que não ativarão o alarme. Você também escolhe se o alarme será mental ou audível.\nUm alarme mental alerta você com um silvo na sua mente, se você estiver a até de 1,5 quilômetro da área protegida. Esse silvo acordará você se você estiver dormindo.\nUm alarme audível produz o som de um sino de mão por 10 minutos num raio de 18 metros.', null),
('Amizade Animal', '1º Círculo', '1 Ação', '9 Metros', 'V, S, M', '24 Horas', 'um punhado de comida', 'Essa magia deixa você convencer uma besta que você não quer prejudicar. Escolha uma besta que você possa ver dentro do alcance. Ela deve ver e ouvir você. Se a Inteligência da besta for 4 ou maior, a magia falha. Do contrário, a besta deve ser bem sucedida num teste de resistência de Sabedoria ou ficará enfeitiçada por você pela duração da magia. Se você ou um dos seus companheiros ferir o alvo, a magia termina.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma besta adicional para cada nível do espaço acima do 1°.'),
('Área Escorregadia', '1º Círculo', '1 Ação', '18 Metros', 'V, S, M', '1 Minuto', 'um pouco de pele de porco ou manteiga', 'Graxa escorregadia cobre o solo em um quadrado de 3 metros centrado em um ponto, dentro do alcance, tornando essa área em terreno difícil pela duração.\nQuando a graxa aparece, cada criatura de pé na área deve ser bem sucedida num teste de resistência de Destreza ou cairá no chão. Uma criatura que entre na área ou termine seu turno nela, deve ser bem sucedido num teste de resistência de Destreza ou cairá no chão.', null),
('Armadura Arcana', '1º Círculo', '1 Ação', 'Toque', 'V, S, M', '8 Horas', 'um pedaço de couro curado', 'Você toca uma criatura voluntária que não esteja vestindo armadura e uma energia mágica protetora a envolve até a magia acabar. A CA base do alvo se torna 13 + o modificador de Destreza dele. A magia acaba se o alvo colocar uma armadura ou se você dissipa-la usando uma ação.', null),
('Armadura de Agathys', '1º Círculo', '1 Ação', 'Pessoal', 'V, S, M', '1 Hora', 'um copo de água', 'Uma força magica protetora envolve você, manifestando- se como um frio espectral que cobre você e seu equipamento. Você ganha 5 pontos de vida temporários pela duração. Se uma criatura atingir você com um ataque corpo-a-corpo enquanto estiver com esses pontos de vida, a criatura sofrerá 5 de dano de frio.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, tanto os pontos de vida temporários quanto o dano de frio aumentam em 5 para cada nível do espaço acima do 1°.'),
('Auxílio Divino', '1º Círculo', '1 Ação Bônus', 'Pessoal', 'V, S', 'Até 1 minuto', null, 'Sua oração fortalece você com radiação divina. Até o fim da magia, seus ataques com arma causam 1d4 de dano radiante extra ao atingirem.', null),
('Benção', '1º Círculo', '1 Ação', '9 Metros', 'V, S, M', 'Até 1 minuto', 'um borrifo de água benta', 'Você abençoa até três criaturas, à sua escolha, dentro do alcance. Sempre que um alvo realizar uma jogada de ataque ou teste de resistência antes da magia acabar, o alvo pode jogar um d4 e adicionar o valor jogado ao ataque ou teste de resistência.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°.'),
('Bom Fruto', '1º Círculo', '1 Ação', 'Toque', 'V, S, M', 'Instantânea', 'um raminho de visco', 'Até dez frutos aparecem na sua mão e são infundidos com magia pela duração. Uma criatura pode usar sua ação para comer um fruto. Comer um fruto restaura 1 ponto de vida e um fruto produz nutrientes suficientes para sustentar uma criatura por um dia.\nOs frutos perdem seu potencial se não forem consumidos dentro de 24 horas da conjuração dessa magia.', null),
('Braços de Hadar', '1º Círculo', '1 Ação', 'Pessoal', 'V, S', 'Instantânea', null, 'Você invoca o poder de Hadar, o Faminto Sombrio. Tentáculos de energia negra brotam de você e golpeiam todas as criaturas a até 3 metros de você. Cada criatura na área deve realizar um teste de resistência de Força. Se falhar, o alvo sofre 2d6 de dano necrótico e não pode fazer reações até o próximo turno dela. Em um sucesso, uma criatura sofre metade do dano e não sofre qualquer outro efeito.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1°.'),
('Bruxaria', '1º Círculo', '1 Ação Bônus', '18 Metros', 'V, S, M', 'Até 1 hora', 'o olho petrificado de um tritão', 'Você coloca uma maldição em uma criatura que você possa ver, dentro do alcance. Até a magia acabar, você causa 1d6 de dano necrótico extra no alvo sempre que atingi-lo com um ataque. Além disso, escolha uma habilidade quando você conjurar a magia. O alvo tem desvantagem em testes de habilidade feitos com a habilidade escolhida.\nSe o alvo cair a 0 pontos de vida antes da magia acabar, você pode usar uma ação bônus, em um turno subsequente, para amaldiçoar outra criatura.\nUma magia remover maldição conjurada no alvo acaba com a magia prematuramente.', 'Quando você conjurar essa magia usando um espaço de magia de 3° ou 4° nível, você poderá manter sua concentração na magia por até 8 horas. Quando você usar um espaço de magia de 5° nível ou superior, você poderá manter sua concentração na magia por até'),
('Comando', '1º Círculo', '1 Ação', '18 Metros', 'V', '1 Rodada', null, 'Você pronuncia uma palavra de comando para uma criatura que você possa ver dentro do alcance. O alvo deve ser bem sucedido num teste de resistência de Sabedoria ou seguirá seu comando no próximo turno dele. A magia não tem efeito se o alvo for um morto-vivo, se ele não entender seu idioma ou se o comando for diretamente nocivo a ele.\nAlguns comandos típicos e seus efeitos a seguir. Você pode proferir um comando diferente dos descritos aqui. Se o fizer, o Mestre descreve como o alvo reage. Se o alvo não puder cumprir o comando, a magia termina.\n\nAproxime-se. O alvo se move para próximo de você o máximo que puder na rota mais direta, terminando seu turno, se ele se mover a até 1,5 metro de você.\n\nLargue. O alvo larga o que quer que ele esteja segurando, e termina seu turno.\n\nFuja. O alvo gasta seu turno se movendo para longe de você da forma mais rápida que puder.\n\nDeite-se. O alvo deita-se no chão e então, termina seu turno.\n\nParado. O alvo não se move e não realiza nenhuma ação. Uma criatura voadora continua no alto, considerando que ela seja capaz de fazê-lo. Se ela tiver que se mover para continuar no alto, ela voa a mínima distância necessária para permanecer no ar.', 'Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°. As criaturas devem estar a 9 metros entre si para serem afetadas.'),
('Compreender Idiomas', '1º Círculo', '1 Ação', 'Pessoal', 'V, S, M', '1 Hora', 'uma pitada de fuligem e sal', 'Pela duração, você compreende o significado literal de qualquer idioma falado que você ouvir. Você também compreende qualquer idioma escrito que vir, mas você deve tocar a superfície onde as palavras estão escritas. Leva, aproximadamente, 1 minuto para ler uma página de texto.\nEssa magia não decifra mensagens secretas em textos ou glifos, como um selo arcano, que não seja parte de um idioma escrito.', null),
('Constrição', '1º Círculo', '1 Ação', '27 Metros', 'V, S', 'Até 1 minuto', null, 'Ervas e vinhas poderosas brotam do solo num quadrado de 6 metros a partir de um ponto dentro do alcance. Pela duração, essas plantas transformam o solo na área em terreno difícil.\nUma criatura na área quando você conjurar a magia deve ser bem sucedida num teste de resistência de Força ou ficará impedida pelo emaranhado de plantas, até a magia acabar. Uma criatura impedida pelas plantas pode usar sua ação para realizar um teste de Força, contra a CD da magia. Se for bem sucedido, irá se libertar.\nQuando a magia termina, as plantas conjuradas murcharão.', null),
('Curar Ferimentos', '1º Círculo', '1 Ação', 'Toque', 'V, S', 'Instantânea', null, 'Uma criatura que você tocar recupera uma quantidade de pontos de vida igual a 1d8 + seu modificador de habilidade de conjuração. Essa magia não produz efeito em mortos-vivos ou constructos.', 'Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, a cura aumenta em 1d8 para cada nível do espaço acima do 1°.'),
('Criar ou Destruir Água', '1º Círculo', '1 Ação', '9 Metros', 'V, S, M', 'Instantânea', 'uma gota de água se estiver criando ou alguns grãos de areia se estiver destruindo', 'Você pode tanto criar quanto destruir água.\n\nCriar Água. Você cria 30 litros de água limpa dentro do alcance, em um recipiente aberto. Alternativamente, a água pode cair como chuva em um cubo de 9 metros dentro do alcance, extinguindo chamas expostas na área.\n\nDestruir Água. Você destrói até 30 litros de água de um recipiente aberto dentro do alcance. Alternativamente, você pode destruir um nevoeiro em um cubo de 9 metros dentro do alcance.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode criar ou destruir 30 litros de água adicionais, ou o tamanho do cubo aumenta em 1,5 metro, para cada nível do espaço acima do 1°.'),
('Convocar Familiar', '1º Círculo', '1 Hora', '3 Metros', 'V, S, M', 'Instantânea', 'carvão, incenso e ervas no valor de 10 po, que devem ser consumidos pelo fogo em um braseiro de bronze.', 'Você adquire os serviços de uma familiar, um espírito que toma a forma de um animal, à sua escolha: aranha, caranguejo, cavalo marinho, coruja, corvo, doninha, gato, falcão, lagarto, morcego, peixe (arenque), polvo, rato, rã (sapo) ou serpente venenosa. Aparecendo em um espaço desocupado dentro do alcance, o familiar tem as mesmas estatísticas da forma escolhida, no entanto, ele é um celestial, corruptor ou fada (à sua escolha) ao invés de uma besta.\n\nSeu familiar até independentemente de você, mas ele sempre obedece aos seus comandos. Em combate, ele rola sua a própria iniciativa e age no seu próprio turno. Um familiar não pode atacar, mas ele pode realizar outras ações, como de costume.\n\nQuando um familiar cai a 0 pontos de vida, ele desaparece, não deixando qualquer corpo físico para trás. Ele reaparece depois de você conjurar essa magia novamente.\n\nEnquanto seu familiar estiver a até 30 metros de você, você pode se comunicar telepaticamente com ele. Além disso, com uma ação, você pode ver através dos olhos do familiar e ouvir através dos ouvidos dele, até o início do seu próximo turno, adquirindo os benefícios de qualquer sentido especial que o familiar possua. Durante esse período, você estará cego e surdo em relação aos seus próprios sentidos.\n\nCom uma ação, você pode, temporariamente, dispensar seu familiar. Ele desaparece dentro de uma bolsa dimensional onde ele aguarda sua convocação. Alternativamente, você pode dispensa-lo para sempre. Com uma ação, enquanto ele estiver temporariamente dispensado, você pode fazê-lo reaparecer em qualquer espaço desocupado a até 9 metros de você.\n\nVocê não pode ter mais de um familiar por vez. Se você conjurar essa magia enquanto já tiver um familiar, ao invés disso, você faz seu familiar existente adotar uma nova forma. Escolha uma das formas da lista acima. Seu familiar se transforma na criatura escolhida.\n\nFinalmente, quando você conjura uma magia com alcance de toque, seu familiar pode transmitir a magia, como se ele tivesse conjurado ela. Seu familiar precisa estar a até 30 metros de você e deve usar a reação dele para transmitir a magia quando você a conjurar. Se a magia necessitar de uma jogada de ataque, você usa seu modificador de ataque para essa jogada.', null),
('Destruição Colérica', '1º Círculo', '1 Ação Bônus', 'Pessoal', 'V', 'Até 1 minuto', null, 'Da próxima vez que você atingir com um ataque corpo-a- corpo com arma enquanto essa magia durar, seu ataque causará 1d6 de dano psíquico extra. Além disso, se o alvo for uma criatura, ele deve realizar um teste de resistência de Sabedoria ou ficará amedrontado por você até a magia acabar. Com uma ação, a criatura pode realizar um teste de resistência de Sabedoria contra a CD da magia para se manter resoluto e terminar a magia.', null),
('Destruição Lancinante', '1º Círculo', '1 Ação Bônus', 'Pessoal', 'V', 'Até 1 minuto', null, 'Da próxima vez que você atingir uma criatura com um ataque corpo-a-corpo com arma enquanto essa magia durar, sua arma flameja com intensas chamas brancas e o ataque causa 1d6 de dano de fogo extra ao alvo, fazendo-o incendiar pelas chamas. No início de cada turno dele, até a arma acabar, o alvo deve realizar um teste de resistência de Constituição. Se falhar na resistência, ele sofre 1d6 de dano de fogo. Se passar na resistência, a magia acaba. Se o alvo ou uma criatura a 1,5 metro dele usar uma ação para apagar as chamas ou se algum outro efeito extinguir as chamas (como submergir o alvo em água), a magia acaba.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano extra inicial causado por esse ataque aumenta em 1d6 para cada nível do espaço acima do 1°.'),
('Destruição Trovejante', '1º Círculo', '1 Ação Bônus', 'Pessoal', 'V', 'Até 1 minuto', null, 'Da primeira vez que você atingir um ataque corpo-a-corpo com arma enquanto essa magia durar, sua arma é rodeada por trovões que são audíveis a até 90 metros de você e o ataque causa 2d6 de dano trovejante extra no alvo. Além disso, se o alvo for uma criatura, ele deve ser bem sucedido num teste de resistência de Força ou será empurrado 3 metros para longe de você e cairá no chão.', null),
('Detectar o Bem e Mal', '1º Círculo', '1 Ação', 'Pessoal', 'V, S', 'Até 10 minutos', null, 'Pela duração, você sabe se existe uma aberração, celestial, corruptor, elemental, fada ou morto-vivo, a até 9 metros de você, assim como onde a criatura está localizada. Similarmente, você sabe se existe um local ou objeto, a até 9 metros de você, que tenha sido consagrado ou profanado magicamente.\n\nA magia pode penetrar a maioria das barreiras, mas é bloqueada por 30 centímetros de rocha, 2,5 centímetros de metal comum, uma fina camada de chumbo, ou 90 centímetros de madeira ou terra.', null),
('Detectar Magia', '1º Círculo', '1 Ação', 'Pessoal', 'V, S', 'Até 10 minutos', null, 'Pela duração, você sente a presença de magia a até 9 metros de você. Se você sentir magia dessa forma, você pode usar sua ação para ver uma aura suave em volta de qualquer criatura ou objeto visível, na área que carrega magia, e você descobre a escolha de magia, se houver uma.\n\nA magia pode penetrar a maioria das barreiras, mas é bloqueada por 30 centímetros de rocha, 2,5 centímetros de metal comum, uma fina camada de chumbo, ou 90 centímetros de madeira ou terra.', null),
('Detectar Veneno e Doença', '1º Círculo', '1 Ação', 'Pessoal', 'V, S, M', 'Até 10 minutos', 'uma folha de teixo', 'Pela duração, você sente a presença e localização de venenos, criaturas venenosas e doenças a até 9 metros de você. Você também identifica o tipo de veneno, criatura venenosa ou doença em cada caso.\n\nA magia pode penetrar a maioria das barreiras, mas é bloqueada por 30 centímetros de rocha, 2,5 centímetros de metal comum, uma fina camada de chumbo, ou 90 centímetros de madeira ou terra.', null),
('Disco Flutuante de Tenser', '1º Círculo', '1 Ação', '9 Metros', 'V, S, M', '1 Hora', 'uma gota de mercúrio', 'Essa magia cria um plano horizontal, circular de energia de 90 cm de diâmetro por 2,5 cm de espessura, que flutua 90 centímetros acima do chão em um espaço desocupado, à sua escolha, que você possa ver dentro do alcance. O disco permanece pela duração e pode suportar até 250 quilos. Se mais peso for colocado nele, a magia termina, e tudo em cima do disco cai no chão.\n\nO disco é imóvel enquanto você estiver a até 6 metros dele. Se você se afastar a mais de 6 metros dele, o disco seguirá você, mantendo-se a 6 metros de você. Ele pode atravessar terreno irregular, subir ou descer escadas, encostas e similares, mas ele não pode atravessar mudanças de elevação de 3 metros ou mais. Por exemplo, o disco não pode atravessar um fosso de 3 metros de profundidade nem poderia sair de tal fosso se tivesse sido criado no fundo dele.\n\nSe você se afastar mais de 30 metros do disco (tipicamente por ele não poder rodear um obstáculo para seguir você), a magia acaba.', null),
('Disfarçar-Se', '1º Círculo', '1 Ação', 'Pessoal', 'V, S', '1 Hora', null, 'Você faz com que você mesmo – incluindo suas roupas, armadura, armas e outros pertences no seu personagem – pareça diferente até a magia acabar ou até você usar sua ação para dispensa-la. Você pode se parecer 30 centímetros mais baixo ou mais alto, e pode parecer magro, gordo ou entre ambos. Você não pode mudar o tipo do seu corpo, portanto, você deve adotar uma forma que tenha a mesma disposição básica de membros. No mais, a extensão da sua ilusão cabe a você.\n\nAs mudanças criadas por essa magia não conseguem se sustentar perante uma inspeção física. Por exemplo, se você usar essa magia para adicionar um chapéu ao seu visual, objetos que passarem pelo chapéu e qualquer um que tocá-lo não sentirá nada ou sentirá sua cabeça e cabelo. Se você usar essa magia para aparentar ser mais magro do que é, a mão de alguém que a erguer para tocar em você, irá esbarrar em você enquanto ainda está, aparentemente, está no ar.\n\nPara perceber que você está disfarçado, uma criatura pode usar a ação dela para inspecionar sua aparência e deve ser bem sucedida em um teste de Inteligência (Investigação) contra a CD da sua magia.', null),
('Duelo Compelido', '1º Círculo', '1 Ação Bônus', '9 Metros', 'V', 'Até 1 minuto', null, 'Você tenta compelir uma criatura a duelar com você. Uma criatura que você possa ver, dentro do alcance, deve realizar um teste de resistência de Sabedoria. Se falhar, a criatura é atraída por você, compelida pela sua exigência divina. Pela duração, ela tem desvantagem nas jogadas de ataque contra criaturas diferentes de você e deve realizar um teste de resistência de Sabedoria cada vez que tentar se mover para um espaço que esteja a mais de 9 metros de você; se ela passar no teste de resistência, essa magia não restringirá o movimento do alvo nesse turno.\n\nA magia termina se você atacar qualquer outra criatura, se você conjurar uma magia que afete uma criatura hostil diferente do alvo, se uma criatura amigável a você causar dano ou conjurar uma magia nociva nele ou se você terminar seu turno a mais de 9 metros do alvo.', null),
('Enfeitiçar Pessoa', '1º Círculo', '1 Ação', '9 Metros', 'V, S', '1 Hora', null, 'Você tenta enfeitiçar um humanoide que você possa ver dentro do alcance. Ele deve realizar um teste de resistência de Sabedoria, e recebe vantagem nesse teste se você ou seus companheiros estiverem lutando com ele. Se ele falhar, ficará enfeitiçado por você até a magia acabar ou até você ou seus companheiros fizerem qualquer coisa nociva contra ele. A criatura enfeitiçada reconhece você como um conhecido amigável. Quando a magia acabar, a criatura saberá que foi enfeitiçada por você.', 'Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°. As criaturas devem estar a até 9 metros umas das outras quando você for afeta-las.'),
('Escudo Arcano', '1º Círculo', '1 Reação', 'Pessoal', 'V, S', '1 Rodada', 'Reação que você faz quando é atingido por um ataque ou alvo da magia mísseis mágicos.', 'Uma barreira de energia invisível aparece e protege você. Até o início do seu próximo turno, você recebe +5 de bônus na CA, incluindo contra o ataque que desencadeou a magia, e você não sofre dano de mísseis mágicos.', null),
('Escudo da Fé', '1º Círculo', '1 Ação Bônus', '18 Metros', 'V, S, M', 'Até 10 minutos', 'um pequeno pergaminho com alguns textos sagrados escritos nele', 'Um campo cintilante aparece ao redor de uma criatura, à sua escolha, dentro do alcance, concedendo +2 de bônus na CA pela duração.', null),
('Escrita Ilusória', '1º Círculo', '1 Minuto', 'Toque', 'S, M', '10 Dias', 'uma tinta à base de chumbo valendo, no mínimo, 10 PO, que é consumida pela magia', 'Você escreve em um pergaminho, papel ou qualquer outro material adequado e tinge ele com uma poderosa ilusão que permanece pela duração.\n\nPara você e para qualquer criatura que você designar quando você conjura essa magia, a escrita parece normal, escrita com a sua caligrafia e transmite qualquer que seja a mensagem que você desejava quando escreveu o texto. Para todos os outros, a escrita aparece como se tivesse sido escrita com uma caligrafia desconhecida ou mágica que é inteligível. Alternativamente, você pode fazer a escrita parecer uma mensagem totalmente diferente, escrita com uma caligrafia e idioma diferentes, apesar de o idioma precisar ser um que você conheça.\n\nNo caso da magia ser dissipada, tanto a escrita original quanto a ilusória desaparecem.\n\nUma criatura com visão verdadeira pode ler a mensagem escondida.', null),
('Falar com Animais', '1º Círculo', '1 Ação', 'Pessoal', 'V, S', '10 Minutos', null, 'Você adquire a habilidade de compreender e se comunicar verbalmente com bestas, pela duração. O conhecimento e consciência de muitas bestas é limitado pela inteligência delas mas, no mínimo, as bestas poderão dar informações a você sobre os locais e monstros próximos, incluindo tudo que eles possam perceber ou tenham percebido no dia anterior. Você pode tentar persuadir uma besta a lhe prestar um favor, à critério do Mestre.', null),
('Falar com Plantas', '1º Círculo', '1 Ação', 'Pessoal', 'V, S', '10 Minutos', null, 'Você imbui as plantas a até 9 metros de você com consciência e animação limitadas, dando-lhes a habilidade de se comunicar com você e seguir seus comandos simples. Você pode perguntar as plantas sobre eventos na área da magia, acontecidos desde o dia anterior, recebendo informações sobre criaturas que passaram, clima e outras circunstâncias.\n\nVocê também pode tornar terreno difícil causado pelo crescimento de plantas (como arbustos e vegetação rasteira) em terreno normal, permanecendo assim pela duração. Ou você pode tornar terreno normal onde as plantas estiverem presentes, em terreno difícil, permanecendo assim pela duração, fazendo as vinhas e ramos atrasarem perseguidores, por exemplo.\n\nAs plantas podem ser capazes de realizar outras tarefas em seu favor, à critério do Mestre. A magia não permite que as plantas desenraizem-se e se movam, mas elas podem mover, livremente, seus ramos, galhos e caules.\n\nSe uma criatura planta estiver na área, você pode se comunicar com ela se você partilhar um idioma em comum, mas você não recebe qualquer habilidade mágica para influencia-la. Essa magia pode fazer as plantas criadas pela magia constrição soltarem uma criatura impedida.', null),
('Fogo das Fadas', '1º Círculo', '1 Ação', '18 Metros', 'V', 'Até 1 minuto', null, 'Cada objeto num cubo de 6 metros dentro do alcance fica delineado com luz azul, verde ou violeta (à sua escolha). Qualquer criatura na área, quando a magia é conjurada, também fica delineada com luz, se falhar num teste de resistência de Destreza. Pela duração, os objetos e criaturas afetadas emitem penumbra num raio de 3 metros.\n\nQualquer jogada de ataque contra uma criatura afetada ou objeto tem vantagem, se o atacante puder ver o alvo e, a criatura afetada ou objeto não recebe benefício por estar invisível.', null),
('Golpe Constritor', '1º Círculo', '1 Ação Bônus', 'Pessoal', 'V', 'Até 1 minuto', null, 'Da próxima vez que você atingir uma criatura com um ataque com arma, antes do final da magia, um emaranhado maciço de vinhas espinhentas aparecem no local do impacto e o alvo deve ser bem sucedido num teste de resistência de Força ou ficará impedido pelas vinhas mágicas, até o fim da magia. Uma criatura Grande ou maior tem vantagem no seu teste de resistência. Se o alvo for bem sucedido na resistência, as vinhas murcharão.\n\nEnquanto estiver impedido pela magia, um alvo sofre 1d6 de dano perfurante no início de cada um dos turnos dele. Uma criatura impedida pelas vinhas ou uma que possa tocar a criatura, pode usar sua ação para realizar um teste de Força contra a CD da magia. Num sucesso, o alvo é libertado.', 'Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1°.'),
('Heroísmo', '1º Círculo', '1 Ação', 'Toque', 'V, S', 'Até 1 minuto', null, 'Uma criatura voluntária que você tocar é imbuída com bravura. Até a magia acabar, a criatura é imune a ser amedrontada e ganha pontos de vida temporários igual ao seu modificador de habilidade de conjuração, no início de cada turno dela. Quando a magia acabar, o alvo perde qualquer ponto de vida temporário restante dessa magia.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°.'),
('Identificação', '1º Círculo', '1 Minuto', 'Toque', 'V, S, M', 'Instantânea', 'uma perola valendo, no mínimo, 100 PO e uma pena de coruja', 'Você escolhe um objeto que você deve tocar durante toda a conjuração da magia. Se ele for um item mágico ou algum outro objeto imbuído por magia, você descobre suas propriedades e como usá-lo, se exige sintonia para ser usado e quantas cargas ele tem, se aplicável. Você descobre se quaisquer magias estão afetando o item e quais eles são. Se o item foi criado por magia, você descobre que magia o criou.\n\nSe você, ao invés, tocar uma criatura durante toda a conjuração, você descobre quais magias, se houver alguma, estão afetando-a atualmente.', null),
('Imagem Silenciosa', '1º Círculo', '1 Ação', '18 Metros', 'V, S, M', 'Até 10 minutos', 'um pouco de lã', 'Você cria a imagem de um objeto, criatura ou outro fenômeno visual que não tenha mais de 4,5 metros cúbicos. A imagem aparece num ponto, dentro do alcança, e permanece pela duração. A imagem é puramente visual; não é acompanhada por som, cheiro ou outros efeitos sensoriais.\n\nVocê pode usar sua ação para fazer a imagem se mover para qualquer ponto, dentro do alcance. À medida que a imagem muda de lugar, você pode alterar a aparência dela para que seu movimento pareça ser o natural para a imagem. Por exemplo, se você criar uma imagem de uma criatura e move-la, você pode alterar a imagem para que ela pareça estar andando.\n\nInteração física com a imagem, revelará que ela é uma ilusão, já que as coisas podem passar através dela. Uma criatura que usar sua ação para examinar a imagem, pode determinar que ela é uma ilusão com um teste de Inteligência (Investigação) bem sucedido contra a CD da magia. Se uma criatura discernir a ilusão como sendo isso, a criatura poderá ver através da imagem.', null),
('Infligir Ferimentos', '1º Círculo', '1 Ação', 'Toque', 'V, S', 'Instantânea', null, 'Faça um ataque corpo-a-corpo com magia contra uma criatura dentro do alcance. Se atingir, o alvo sofre 3d10 de dano necrótico.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d10 para cada nível acima do 1°.'),
('Leque Cromático', '1º Círculo', '1 Ação', 'Pessoal', 'V, S, M', '1 Rodada', 'um punhado de pó ou areia nas cores vermelha, amarela e azul', 'Um feixe ofuscante de luzes coloridas ordenadas, surge da sua mão. Role 6d10; o total é a quantidade de pontos de vida de criaturas que essa magia pode afetar. As criaturas num cone de 4,5 metros, originado de você, são afetadas em ordem ascendente dos seus pontos de vida (ignorando criaturas inconsciente e que não podem ver).\n\nComeçando com as criaturas que tiverem menos pontos de vida, cada criatura afetada por essa magia ficará cega até o fim da magia. Subtraia os pontos de vida de cada criatura do total antes de considerar os pontos de vida da próxima criatura. Os pontos de vida de uma criatura devem ser iguais ou menores que o total restante para que essa criatura seja afetada.', 'Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, jogue 2d10 adicionais para cada nível do espaço acima do 1°.'),
('Mãos Flamejantes', '1º Círculo', '1 Ação', 'Pessoal', 'V, S', 'Instantânea', null, 'Enquanto você mantiver suas mãos com os polegares juntos e os dedos abertos, uma fino leque de chamas emerge das pontas dos seus dedos erguidos. Cada criatura num cone de 4,5 metros deve realizar um teste de resistência de Destreza. Uma criatura sofre 3d6 de dano de fogo se falhar no teste, ou metade desse dano se obtiver sucesso.\n\nO fogo incendeia qualquer objeto inflamável na área que não esteja sendo vestido ou carregado.', 'Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1°.'),
('Marca do Caçador', '1º Círculo', '1 Ação Bônus', '27 Metros', 'V', 'Até 1 hora', null, 'Você escolhe uma criatura que possa ver, dentro do alcance e a marca misticamente como sua presa. Até a magia acabar, você causa 1d6 de dano extra ao alvo sempre que você o atingir com um ataque com arma e você tem vantagem em quaisquer testes de Sabedoria (Percepção) ou Sabedoria (Sobrevivência) feitos para encontrá-la. Se o alvo cair a 0 pontos de vida antes da magia acabar, você pode usar uma ação bônus, no seu turno subsequente para marcar uma nova criatura.', 'Quando você conjurar essa magia usando um espaço de magia de 3° ou 4° nível, você poderá manter sua concentração na magia por até 8 horas. Quando você usar um espaço de magia de 5° nível ou superior, você poderá manter sua concentração na magia por até 24 horas.'),
('Mísseis Mágicos', '1º Círculo', '1 Ação', '36 Metros', 'V, S', 'Instantânea', null, 'Você cria três dardos brilhantes de energia mística. Cada dardo atinge uma criatura, à sua escolha, que você possa ver, dentro do alcance. Um dardo causa 1d4 + 1 de dano de energia ao alvo. Todos os dardos atingem simultaneamente e você pode direciona-los para atingir uma criatura ou várias.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, a magia cria um dardo adicional para cada nível do espaço acima do 1°.'),
('Névoa Obscurecente', '1º Círculo', '1 Ação', '36 Metros', 'V, S', 'Até 1 hora', null, 'Você cria uma esfera de 6 metros de raio de névoa, centrada num ponto, dentro do alcance. A esfera se espalha, dobrando esquinas, e a área dela é de escuridão densa. Ela permanece pela duração ou até um vento moderado ou mais rápido (pelo menos 15 quilômetros por hora) dispersa-la.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o raio da névoa aumenta em 6 metros para cada nível do espaço acima do 1°.'),
('Onda Trovejante', '1º Círculo', '1 Ação', 'Pessoal', 'V, S', 'Instantânea', null, 'Uma onda de força trovejante varre tudo a partir de você. Cada criatura num cubo de 4,5 metros originado em você, deve realizar um teste de resistência de Constituição. Se falhar na resistência, uma criatura sofrerá 2d8 de dano trovejante e será empurrada 3 metros para longe de você. Se obtive sucesso na resistência, a criatura sofrerá metade desse dano e não será empurrada.\n\nAlém disso, objetos soltos que estiverem completamente dentro da área de efeito serão automaticamente empurrados 3 metros para longe de você pelo efeito da magia e a magia emitirá um ressonante barulho de trovão audível a até 90 metros.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d8 para cada nível acima do 1°.'),
('Orbe Cromática', '1º Círculo', '1 Ação', '27 Metros', 'V, S, M', 'Instantânea', 'um diamante valendo, no mínimo, 50 PO', 'Você arremessa uma esfera de energia de 12 centímetros de diâmetro numa criatura que você possa ver dentro do alcance. Você escolhe ácido, frio, fogo, elétrico, veneno ou trovejante para o tipo de orbe que você cria e, então, realiza um ataque à distância com magia. Se o ataque atingir, a criatura sofre 3d8 de dano do tipo escolhido.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d8 para cada nível do espaço acima do 1°.'),
('Palavra Curativa', '1º Círculo', '1 Ação Bônus', '18 Metros', 'V', 'Instantânea', null, 'Uma criatura, à sua escolha, que você possa ver dentro do alcance recupera uma quantidade de pontos de vida igual a 1d4 + seu modificador de habilidade de conjuração. Essa magia não tem efeito em mortos-vivos ou constructos.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, a cura aumenta em 1d4 para cada nível do espaço acima do 1°.'),
('Passos Longos', '1º Círculo', '1 Ação', 'Toque', 'V, S, M', '1 Hora', 'um pouco de barro', 'Você toca uma criatura. O deslocamento do alvo aumenta em 3 metros, até a magia acabar.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°.'),
('Perdição', '1º Círculo', '1 Ação', '9 Metros', 'V, S, M', 'Até 1 minuto', 'uma gota de sangue', 'Até três criaturas, à sua escolha, que você possa ver dentro do alcance, devem realizar um teste de resistência de Carisma. Sempre que um alvo que falhou nessa resistência realizar uma jogada de ataque ou um teste de resistência antes da magia acabar, o alvo deve rolar um d4 e subtrair o valor rolado da jogada de ataque ou teste de resistência.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°.'),
('Purificar Alimentos', '1º Círculo', '1 Ação', '3 Metros', 'V, S', 'Instantânea', null, 'Toda comida e bebida não-mágica dentro de uma esfera de 1,5 metro de raio centrada num ponto, à sua escolha, dentro do alcance é purificada e se livrada de venenos ou doenças.', null),
('Proteção Contra o Bem e Mal', '1º Círculo', '1 Ação', 'Toque', 'V, S, M', 'Até 10 minutos', 'água benta ou pó de prata e ferro, consumidos pela magia', 'Até a magia acabar, uma criatura voluntária que você tocar estará protegida contra certos tipos de criaturas: aberrações, celestiais, corruptores, elementais, fadas e mortos-vivos.\n\nA proteção garante diversos benefícios. As criaturas desse tipo tem desvantagem nas jogadas de ataque contra o alvo. O alvo não pode ser enfeitiçado, amedrontado ou possuído por elas. Se o alvo já estiver enfeitiçado, amedrontado ou possuído por uma dessas criaturas, o alvo terá vantagem em qualquer novo teste de resistência contra o efeito relevante.', null),
('Queda Suave', '1º Círculo', '1 Reação', '18 Metros', 'V, M', '1 Minutos', 'uma pequena pena ou penugem similar', 'Reação que você realiza quando você ou uma criatura a até 18 metros cair. Escolha até cinco criaturas caindo, dentro do alcance. A taxa de descendência de uma criatura caindo é reduzida para 18 metros por rodada, até o fim da magia. Se a criatura aterrissar antes da magia acabar, ela não sofre nenhum dano de queda, pode aterrissar em pé e a magia termina para essa criatura.', null),
('Raio Adoecente', '1º Círculo', '1 Ação', '18 Metros', 'V, S', 'Instantânea', null, 'Um raio adoecente de energia esverdeada chicoteia na direção de uma criatura dentro do alcance. Faça um ataque à distância com magia contra o alvo. Se atingir, o alvo sofrerá 2d8 de dano de veneno e deve realizar um teste de resistência de Constituição. Se falhar na resistência, ele também ficará envenenado até o final do seu próximo turno.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano da magia aumenta em 1d8 para cada nível do espaço acima do 1°.'),
('Raio de Bruxa', '1º Círculo', '1 Ação', '9 Metros', 'V, S, M', 'Até 1 minuto', 'um galho de uma árvore que tenha sido atingida por um relâmpago', 'Um raio crepitante de energia azul é arremessado em uma criatura dentro do alcance, formando um arco elétrico contínuo entre você e o alvo. Faça um ataque à distância com magia contra a criatura. Se atingir, o alvo sofrerá 1d12 de dano elétrico e, em cada um dos seus turnos, pela duração, você pode usar sua ação para causar 1d12 de dano elétrico ao alvo, automaticamente. A magia acaba se você usar sua ação para fazer qualquer outra coisa. A magia também acaba se o alvo estiver fora do alcance da magia ou se você tiver cobertura total para ele.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano inicial aumenta em 1d12 para cada nível do espaço acima do 1°.'),
('Raio Guiador', '1º Círculo', '1 Ação', '36 Metros', 'V, S', '1 Rodada', null, 'Um lampejo de luz se lança em direção de uma criatura, à sua escolha, dentro do alcance. Realize um ataque à distância com magia contra o alvo. Se atingir, o alvo sofre 4d6 de dano radiante e, a próxima jogada de ataque contra esse alvo, antes do final do seu próximo turno, terá vantagem, graças a penumbra mística cintilando no alvo, até então.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1°.'),
('Recuo Acelerado', '1º Círculo', '1 Ação Bônus', 'Pessoal', 'V, S', 'Até 10 minutos', null, 'Essa magia permite que você se mova a um ritmo incrível. Quando você conjura essa magia e, a partir de então, com uma ação bônus em cada um dos seus turnos, até a magia acabar, você pode realizar a ação de Disparada.', null),
('Repreensão Infernal', '1º Círculo', '1 Reação', '18 Metros', 'V, S', 'Instantânea', null, 'Reação que você faz em resposta ao sofre dano de uma criatura a até 18 metros de você e que você possa ver.\n\nVocê aponta seu dedo e a criatura que causou dano a você é, momentaneamente, envolta por chamas infernais. A criatura deve realizar um teste de resistência de Destreza. Ela sofre 2d10 de dano de fogo se falhar na resistência ou metade desse dano se obtiver sucesso.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d10 para cada nível do espaço acima do 1°.'), 
('Riso Histérico de Tasha', '1º Círculo', '1 Ação', '9 Metros', 'V, S, M', 'Até 1 minuto', 'pequenas tortas e uma pena que é balançada no ar', 'Uma criatura, à sua escolha, que você possa ver, dentro do alcance, acha tudo hilariantemente engraçado e cai na gargalhada, se essa magia afeta-la. O alvo deve ser bem sucedido em um teste de resistência de Sabedoria ou cairá no chão, ficando incapacitado e incapaz de se levantar pela duração. Uma criatura com valor de Inteligência 4 ou inferior não é afetada.\n\nAo final de cada um dos turnos dela e, toda vez que sofrer dano, o alvo pode realizar outro teste de resistência de Sabedoria. O alvo terá vantagem no teste de resistência se ele for garantido por ele ter sofrido dano. Se obtiver sucesso, a magia acaba.', null),
('Salto', '1º Círculo', '1 Ação', 'Toque', 'V, S, M', '1 Minuto', 'uma perna de gafanhoto', 'Você toca uma criatura. A distância de salto da criatura é triplicada até a magia acabar.', null),
('Santuário', '1º Círculo', '1 Ação Bônus', '9 Metros', 'V, S, M', '1 Minuto', 'um pequeno espelho de prata', 'Você protege uma criatura, dentro do alcance, contra ataques. Até a magia acabar, qualquer criatura que tentar atacar ou usar magias que causem dano contra criatura protegida deve, primeiro, realizar um teste de resistência de Sabedoria. Se falhar na resistência, a criatura deve escolher um novo alvo ou perderá o ataque ou magia. Essa magia não protege a criatura contra efeitos de área, como a explosão de uma bola de fogo.\n\nSe a criatura protegida realizar um ataque ou conjurar uma magia que afete uma criatura inimiga, essa magia acaba.', null),
('Saraivada de Espinhos', '1º Círculo', '1 Ação Bônus', 'Pessoal', 'V', 'Até 1 minuto', null, 'Da próxima vez que você atingir uma criatura com um ataque à distância com arma, antes da magia acabar, essa magia cria uma chuva de espinhos que brota da sua arma à distância ou munição. Além do efeito normal do ataque, o alvo do ataque e cada criatura a até 1,5 metro dele, devem realizar um teste de resistência de Destreza. Uma criatura sofre 1d10 de dano perfurante se falhar na resistência ou metade desse dano se obtiver sucesso.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d10 para cada nível do espaço acima do 1° (até o máximo de 6d10).'),
('Servo Invisível', '1º Círculo', '1 Ação', '18 Metros', 'V, S, M', '1 Hora', 'um pedaço de barbante e um pouco de madeira', 'Essa magia cria uma força invisível, sem mente e sem forma que realiza tarefas simples, ao seu comando, até a magia acabar. O servo aparece do nada em um espaço desocupado no chão, dentro do alcance. Ele tem CA 10, 1 ponto de vida, Força 2 e não pode atacar. Se ele cair a 0 pontos de vida, a magia acaba.\n\nUma vez em cada um dos seus turnos, com uma ação bônus, você pode comandar, mentalmente, o servo para se mover até 4,5 metros e interagir com um objeto. O servo pode realizar tarefas simples que um serviçal humano faria, como buscar coisas, limpar, consertar, dobrar roupas, acender chamas, servir comida ou derramar vinho. Uma vez que um comando seja dado, o servo realiza a tarefa da melhor forma possível, até completar a tarefa, então esperará o seu próximo comando.\n\nSe você comandar o servo a realizar uma tarefa que poderia afasta-lo a mais de 18 metros de você, a magia termina.', null),
('Sono', '1º Círculo', '1 Ação', '36 Metros', 'V, S, M', '1 Minuto', 'um punhado de areia fina, pétalas de rosas ou um grilo', 'Essa magia põem as criaturas num entorpecimento mágico. Jogue 5d8; o total é a quantidade de pontos de vida de criaturas afetados pela magia. As criaturas numa área de 6 metros de raio, centrada no ponto escolhido, dentro do alcance, são afetadas em ordem ascendente dos pontos de vida atuais delas (ignorando criaturas inconscientes).\n\nComeçando com as criaturas com menos pontos de vida atuais, cada criatura afetada por essa magia cai inconsciente até a magia acabar, sofrer dano ou alguém usar sua ação para sacudi-la ou esbofeteá-la até acordar. Subtraia os pontos de vida de cada criatura do total antes de seguir para a próxima criatura com menos pontos de vida atuais. Os pontos de vida atuais da criatura devem ser iguais ou menores que o valor restante para que a criatura possa ser afetada.\n\nMortos-vivos e criaturas imunes a serem enfeitiçadas não são afetadas por essa magia.', 'Quando você conjurar essa magia usando um espaço de magia de 2º nível ou superior, jogue 2d8 adicionais para cada nível do espaço acima do 1°.'),
('Sussurros Dissonantes', '1º Círculo', '1 Ação', '18 Metros', 'V', 'Instantânea', null, 'Você sussurra uma melodia dissonante que apenas uma criatura, à sua escolha, dentro do alcance pode ouvir, causando-lhe uma terrível dor. O alvo deve realizar um teste de resistência de Sabedoria. Se falhar na resistência, ele sofrerá 3d6 de dano psíquico e deve, imediatamente, usar sua reação, se disponível, para se mover para o mais longe possível de você. A criatura não se moverá para um terreno obviamente perigoso, como uma fogueira ou abismo. Se obtiver sucesso na resistência, o alvo sofre metade do dano e não precisa se afastar de você. Uma criatura surda obtém sucesso automaticamente na sua resistência.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1°.'),
('Vitalidade Falsa', '1º Círculo', '1 Ação', 'Pessoal', 'V, S, M', '1 Hora', 'uma pequena quantidade de álcool ou bebidas destiladas', 'Reforçando-se com uma vitalidade necromântica ilusória, você ganha 1d4 + 4 pontos de vida temporários pela duração.', 'Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você ganha 5 pontos de vida temporários adicionais para cada nível do espaço de magia acima do 1°.');